const gbs = {
  lockr_prefix: 'TSBEER_',
  USER: {
    SIGNQTY: 'SIGNQTY',
    CARRIERNO: 'CARRIERNO',
    SIGNPRODUCTNAME: 'SIGNPRODUCTNAME',
    MAPSTATUS: 'MAPSTATUS',
    CUSTOMERINCODE: 'CUSTOMERINCODE',
    MAPPOINTINCODE: 'MAPPOINTINCODE',
    MAPCUSTOMERINCODE: 'MAPCUSTOMERINCODE',
    BOTTLELIST: 'BOTTLELIST',
    POINTINCODE: 'POINTINCODE',
    CUSTOMERNAME: 'CUSTOMERNAME',
    POINTNAME: 'POINTNAME',
    LOGIN_NAME: 'LOGIN_NAME',
    OPEN_ID: 'OPEN_ID',
    ROLE_ID: 'ROLE_ID',
    MENUS: 'MENUS',
    PHONE: 'PHONE',
    REMEMBER_ME: 'REMEMBER_ME',
    TOKEN: 'TOKEN',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REDIRECT_URI: 'REDIRECT_URI',
    FACTORY: 'FACTORY',
    TEMP_FACTORY: 'TEMP_FACTORY',
    IS_LOGIN: 'IS_LOGIN',
    ACCOUNT: 'ACCOUNT',
    UUID: 'UUID',
    SHEETNO: 'SHEETNO',
    ORDERNO: 'ORDERNO',
    ITEMNO: 'ITEMNO',
    DRIVERNO: 'DRIVERNO',
    EMPLOYEENAME: 'EMPLOYEENAME'
  },
  SMS: {
    SIGN_CODE_AL: 'SMS_169865225',
    SIGN_CODE: 'RT009',
    SIGN_SMS: 'SIGN_SMS',
    REG_CODE_AL: 'SMS_169865145',
    REG_CODE: 'RT008',
    REG_SMS: 'REG_SMS',
    LOGIN_CODE_AL: 'SMS_169870198',
    LOGIN_CODE: 'RT010',
    LOGIN_SMS: 'LOGIN_SMS'
  },
  Appsecret: '43ee40070264740625a7989119f8ed37'
}
export {
  gbs
}
